### ISSUE TITLE
Audio spectrum sometimes blinks

### ISSUE THREAD

**Issue by rom1v** [fengalin/media-toc#58] opened 2017-10-16 15:45 UTC
During playback, the audio spectrum sometimes "blinks".

I recorded by screen to get a screenshot of the problem:
![flash](https://user-images.githubusercontent.com/543275/31621296-a2cb3590-b299-11e7-999d-6b6aa8d17fd7.png)

Maybe you skip some frames when the content is not ready…

**Comment by fengalin** [comment] 2017-10-16 15:50
Thanks for your report @rom1v !

**Comment by fengalin** [comment] 2017-10-17 18:29
@rom1v could you try with latest master, please? I couldn't reproduce the same problem you experienced, but I had another symptom with the same trailer (in a different container though).

**Comment by rom1v** [comment] 2017-10-17 19:24
I still reproduce the problem (on version 834555b4218f1684f63838f54039e6b0a19fff5f).

**Comment by fengalin** [comment] 2017-10-17 19:49
Ok, thanks for the test! I need to find the exact same version. Do you remember where you downloaded it?

**Comment by rom1v** [comment] 2017-10-17 19:57
I reproduce the issue with any media file, audio or video (not only this one).

I use Debian Stretch + XFCE.

Put the window above another application with a white background (e.g. an empty page in firefox), so that the blinking is more obvious. And make your CPU busy.

**Comment by fengalin** [comment] 2017-10-17 19:57
Oh! Could you also tell me:
- The resolution of the trailer.
- The CPU / GPU you use.

Thanks a lot!
Edit: removed info you provided ;)

**Comment by fengalin** [comment] 2017-10-17 20:01
It doesn't happen here :(
I'll figure out probes to understand. Thanks again for testing.

**Comment by fengalin** [comment] 2017-10-17 23:50
I managed to get a glimpse on the problem by switching from Wayland to Xorg.
I first suspected issues with the UI layout. After removing almost everything, I found out it had to do with the way the video widget is handled. I need to investigate this some more. I'll try to simplify the UI layout also. There are too many nested containers.

**Comment by fengalin** [comment] 2017-10-18 17:35
@rom1v . I changed a couple of things that could solve the problem you found. However, I'm not 100% sure because the only symptom close enough I could see was a flash when the playback reached the end of stream on Xorg. I focused on this one as an indicator of success of my modifications.

Could you tell me if you still experience high CPU usage and flickering with https://github.com/fengalin/media-toc/commit/b60a380d297b7a31aea09e3998abed17deed2115?

The waveform rendering is notably smoother on Wayland than on Xorg, especially with 6 audio channels. I will add a preference to render only the front left and front right channels.

Edit: updated heads's reference as last commit is worth the pull!

**Comment by rom1v** [comment] 2017-10-18 21:14
It seems better, in that it does not show garbage, but it still blinks with the background color :
![bug](https://user-images.githubusercontent.com/543275/31743072-0e1aae4a-b45a-11e7-9c06-b2dc98da86b2.jpg)

PS: you should skip a line after a commit title, otherwise the whole description is considered as the title:

    git log --oneline

**Comment by fengalin** [comment] 2017-10-18 21:28
Could you run the whole trailer with the following command please:
```
cargo run --features trace-audio_controller trace-waveform-buffer trace-waveform-rendering
```

In an Xorg environment I get 4x `AudioController::draw no image` just after the `Opening...`. If you get something else, could you post the output here?

Many thanks for testing, and thanks for your tip about the commits.

**Comment by rom1v** [comment] 2017-10-18 22:20
When I play the movie, except after the `Opening...`, I don't have `AudioController::draw no image`, and it does not blink (anymore).

However, when I seek a lot, I get these logs exactly when it blinks.

**Comment by fengalin** [comment] 2017-10-18 22:30
After a seek it makes sense, because the stream takes time to settle down, so no waveform can be rendered before GStreamer synchronizes the stream. I keep a 30s buffer of samples, so if you seek back within the last 30s approx., the waveform will render as soon as GStreamer has synchronized the position. If you seek to a position out of the buffer, it will take time to get the samples at this position.

So, if I understand correctly, when you don't activate the features above, it blinks, and when you do (which means there is more code to execute), it doesn't... I need some time to feel what's going on!

**Comment by fengalin** [comment] 2017-10-19 14:08
@rom1v , I installed Debian Stretch Xfce in a VM and had no such problem. I suspect the rendering to pressure your system too much. I will had a preference screen which will allow reducing the frame rate and other parameters. Hopefully, that will help.

What are your system's spec. (CPU, RAM, GPU)?

**Comment by rom1v** [comment] 2017-10-19 14:11
> So, if I understand correctly, when you don't activate the features above, it blinks, and when you do (which means there is more code to execute), it doesn't... 

In fact, since your changes, it "blinks" (with the background) only when I seek, which you said is normal.

**Comment by fengalin** [comment] 2017-10-19 14:50
Oh! That would be great, and even better if it didn't blink at all! But, just to be sure, you're not supposed to run the application with the extra `--features ...` except for debugging purposes. So if it still blinks with a regular `cargo run --release`, I still might try some more.

**Comment by rom1v** [comment] 2017-10-20 06:23
> So if it still blinks with a regular `cargo run --release`, I still might try some more.

It does not, if I don't seek :)

**Comment by fengalin** [comment] 2017-10-22 18:39
@rom1v , I may have fixed the blinking after a seek. Tell me if it seems better. I'm still not satisfied with a flickering effect on some samples, but I'll address it in a separate issue.

**Comment by fengalin** [comment] 2017-10-25 16:08
@rom1v , I'm closing this issue. Feel free to comment if you get a chance to test latest master.

**Closed as completed** 2017-10-30 21:23 UTC
Labels: bug
